frase = str(input('Digite uma frase: ')).strip().upper()
validandoLetraA = frase.count('A')
positionLetraA = frase.find('A')
print(f'A frase digitada foi {frase}')
print(f'A frase digitada contem {frase.count("A")} letra(s) A')
print(f'A letra A na primeira posição é >> {positionLetraA + 1}')
print(f'E a útima posição é {frase.rfind("A") + 1}')