num = float (input('Conversão de medidas >>> Digite um numero: '))
print(f'o valor digitado é {num} metros, segue a baixo o valor em outras medidas >>>')
print(f'Conversão para Centimetros é {num * 100}.')
print(f'Conversão para Milimetros é {num * 1000}.')
print(f'Conversão para Dam ( Decâmetro ) é {num * 10}')
print(f'Conversão para Dm ( Decimetro ) é {num / 10}.')
print(f'Conversão para Hm ( Hectômetro ) é {num / 100}.')
print(f'Conversão para Km é {num / 1000}.')
