textoString = str('Seja muito bem vindo ao curso de Python')
textoMaiuscula = textoString.upper()
textoMinuscula = textoString.lower()
textoLista = textoString.split()
print(textoString[0:5])
print(textoString[5:11])
print(textoString[11:15])
print(textoString[15:20])
print(textoString[21:23])
print(textoString[24:29])
print(textoString[30:32])
print(textoString[33:])
print(textoMaiuscula, textoMinuscula)
print(textoLista)
print(textoLista[-1].upper())
